version: '3.8'

services:
  app:
    build: .
    ports:
      - "8282:8282"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres # Use internal port 5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./log/finTech:/log/finTech
    networks:
      - app-network

  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432" # Map host 5433 to container 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge