server:
  port: 8282
  servlet:
    context-path: /

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres} # Use host port 5433
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Tashkent
  main:
    allow-bean-definition-overriding: true

#SWAGGER
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs
  override-with-generic-response: false

#Logging configuration
logging:
  file:
    path: /log/finTech
  level:
    root: info
  logback:
    rolling-policy:
      max-history: 365
      clean-history-on-start: false
      max-file-size: 20MB
